Clean errors for missing package roots.
Before:
$ hidl-gen -Lcheck a.b.c@1.0
hidl-gen F 02-20 11:09:59 210330 210330 Coordinator.cpp:338] Check failed: ret != mPackageRoots.end() Unable to find package root for a.b.c@1.0
Aborted

After:
$ hidl-gen -Lcheck a.b.c@1.0
ERROR: Package root not specified for a.b.c@1.0

The previous abort error confused several and also incorrectly indicated
that it was an internal error in hidl-gen ('Check failed' 'Aborted') rather
than indicating an error in the command-line arguments.

Fixes: 73649477
Test: hidl's run_all_host_tests.sh, update-makefiles works, + manual
Change-Id: Iedba2cddd2509f90862cbcc4af1462e9ba54f218