Remove unused jar manifest file from ddmlib-prebuilt.jar
This fixed build race condition introduced by hidden dependency on
kxml2-2.3.0.jar, which is also a prebuilt module when we build the SDK.
The build error looks like:
error: error reading out/host/darwin-x86/framework/kxml2-2.3.0.jar;
cannot read zip file
make: ***
[out/host/common/obj/JAVA_LIBRARIES/dumpeventlog_intermediates/javalib.jar]
Error 41

Change-Id: I55a84e031e295df88179331fde9a54c4feff492b