Better error detection.
Note, had to use ` instead of ' or " because otherwise bison adds
  unnecessary quotes in error messages.

Example:
ERROR: syntax error, unexpected keyword `import` ...
ERROR: syntax error, unexpected type, expecting identifier at ...

Test: manual
Fixes: 62135419

Change-Id: I3ef1b2f660629a9a95286dcdbfa7be5aa7c9b387